<?php
/**
 * TimeEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Time
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Time API
 *
 * ConnectWise Time API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Time;

/**
 * TimeEntryTest Class Doc Comment
 *
 * @category    Class */
// * @description TimeEntry
/**
 * @package     Spinen\ConnectWise\Clients\Time
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TimeEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "TimeEntry"
     */
    public function testTimeEntry()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "charge_to_id"
     */
    public function testPropertyChargeToId()
    {

    }

    /**
     * Test attribute "charge_to_type"
     */
    public function testPropertyChargeToType()
    {

    }

    /**
     * Test attribute "member"
     */
    public function testPropertyMember()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "business_unit_id"
     */
    public function testPropertyBusinessUnitId()
    {

    }

    /**
     * Test attribute "work_type"
     */
    public function testPropertyWorkType()
    {

    }

    /**
     * Test attribute "work_role"
     */
    public function testPropertyWorkRole()
    {

    }

    /**
     * Test attribute "agreement"
     */
    public function testPropertyAgreement()
    {

    }

    /**
     * Test attribute "time_start"
     */
    public function testPropertyTimeStart()
    {

    }

    /**
     * Test attribute "time_end"
     */
    public function testPropertyTimeEnd()
    {

    }

    /**
     * Test attribute "hours_deduct"
     */
    public function testPropertyHoursDeduct()
    {

    }

    /**
     * Test attribute "actual_hours"
     */
    public function testPropertyActualHours()
    {

    }

    /**
     * Test attribute "billable_option"
     */
    public function testPropertyBillableOption()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "internal_notes"
     */
    public function testPropertyInternalNotes()
    {

    }

    /**
     * Test attribute "add_to_detail_description_flag"
     */
    public function testPropertyAddToDetailDescriptionFlag()
    {

    }

    /**
     * Test attribute "add_to_internal_analysis_flag"
     */
    public function testPropertyAddToInternalAnalysisFlag()
    {

    }

    /**
     * Test attribute "add_to_resolution_flag"
     */
    public function testPropertyAddToResolutionFlag()
    {

    }

    /**
     * Test attribute "email_resource_flag"
     */
    public function testPropertyEmailResourceFlag()
    {

    }

    /**
     * Test attribute "email_contact_flag"
     */
    public function testPropertyEmailContactFlag()
    {

    }

    /**
     * Test attribute "email_cc_flag"
     */
    public function testPropertyEmailCcFlag()
    {

    }

    /**
     * Test attribute "email_cc"
     */
    public function testPropertyEmailCc()
    {

    }

    /**
     * Test attribute "hours_billed"
     */
    public function testPropertyHoursBilled()
    {

    }

    /**
     * Test attribute "entered_by"
     */
    public function testPropertyEnteredBy()
    {

    }

    /**
     * Test attribute "date_entered"
     */
    public function testPropertyDateEntered()
    {

    }

    /**
     * Test attribute "invoice"
     */
    public function testPropertyInvoice()
    {

    }

    /**
     * Test attribute "hourly_rate"
     */
    public function testPropertyHourlyRate()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {

    }

}
