<?php
/**
 * ScheduleStopwatchesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Time
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Time API
 *
 * ConnectWise Time API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Time;

use \Spinen\ConnectWise\Clients\Time\Configuration;
use \Spinen\ConnectWise\Clients\Time\ApiClient;
use \Spinen\ConnectWise\Clients\Time\ApiException;
use \Spinen\ConnectWise\Clients\Time\ObjectSerializer;

/**
 * ScheduleStopwatchesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Time
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScheduleStopwatchesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for timeSchedulestopwatchesCountGet
     *
     * .
     *
     */
    public function testTimeSchedulestopwatchesCountGet()
    {

    }

    /**
     * Test case for timeSchedulestopwatchesGet
     *
     * .
     *
     */
    public function testTimeSchedulestopwatchesGet()
    {

    }

    /**
     * Test case for timeSchedulestopwatchesIdDelete
     *
     * .
     *
     */
    public function testTimeSchedulestopwatchesIdDelete()
    {

    }

    /**
     * Test case for timeSchedulestopwatchesIdGet
     *
     * .
     *
     */
    public function testTimeSchedulestopwatchesIdGet()
    {

    }

    /**
     * Test case for timeSchedulestopwatchesIdPatch
     *
     * .
     *
     */
    public function testTimeSchedulestopwatchesIdPatch()
    {

    }

    /**
     * Test case for timeSchedulestopwatchesIdPut
     *
     * .
     *
     */
    public function testTimeSchedulestopwatchesIdPut()
    {

    }

    /**
     * Test case for timeSchedulestopwatchesPost
     *
     * .
     *
     */
    public function testTimeSchedulestopwatchesPost()
    {

    }

}
