<?php
/**
 * TicketStopwatchesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Time
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Time API
 *
 * ConnectWise Time API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Time;

use \Spinen\ConnectWise\Clients\Time\Configuration;
use \Spinen\ConnectWise\Clients\Time\ApiClient;
use \Spinen\ConnectWise\Clients\Time\ApiException;
use \Spinen\ConnectWise\Clients\Time\ObjectSerializer;

/**
 * TicketStopwatchesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Time
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TicketStopwatchesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for timeTicketstopwatchesCountGet
     *
     * .
     *
     */
    public function testTimeTicketstopwatchesCountGet()
    {

    }

    /**
     * Test case for timeTicketstopwatchesGet
     *
     * .
     *
     */
    public function testTimeTicketstopwatchesGet()
    {

    }

    /**
     * Test case for timeTicketstopwatchesIdDelete
     *
     * .
     *
     */
    public function testTimeTicketstopwatchesIdDelete()
    {

    }

    /**
     * Test case for timeTicketstopwatchesIdGet
     *
     * .
     *
     */
    public function testTimeTicketstopwatchesIdGet()
    {

    }

    /**
     * Test case for timeTicketstopwatchesIdPatch
     *
     * .
     *
     */
    public function testTimeTicketstopwatchesIdPatch()
    {

    }

    /**
     * Test case for timeTicketstopwatchesIdPut
     *
     * .
     *
     */
    public function testTimeTicketstopwatchesIdPut()
    {

    }

    /**
     * Test case for timeTicketstopwatchesPost
     *
     * .
     *
     */
    public function testTimeTicketstopwatchesPost()
    {

    }

}
